"""Build the static dashboard data file from model output CSVs.

Run from the repository root:
    python scripts/update_dashboard.py
"""

from __future__ import annotations

import csv
import json
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ROOT / "outputs"
DESTINATION = ROOT / "docs" / "data" / "dashboard-data.js"


def read_csv(name: str) -> list[dict[str, str]]:
    path = OUTPUTS / name
    if not path.exists():
        return []
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def number(row: dict[str, str], key: str, default: float = 0.0) -> float:
    try:
        return float(row[key])
    except (KeyError, TypeError, ValueError):
        return default


def build_dashboard() -> dict:
    summaries = read_csv("model_summary.csv")
    picks = read_csv("weekly_picks.csv")

    strategies = [
        {"name": row["strategy"], "points": number(row, "confidence_points")}
        for row in summaries
    ]
    market = next((row for row in summaries if row["strategy"] == "Market"), {})
    full_model = next((row for row in summaries if row["strategy"] == "Full model"), {})
    best = max(summaries, key=lambda row: number(row, "confidence_points"), default={})

    week = picks[0].get("week", "Awaiting current schedule") if picks else "Awaiting current schedule"
    rendered_picks = [
        {
            "rank": int(number(row, "rank")),
            "pick": row.get("pick", "TBD"),
            "opponent": row.get("opponent", "TBD"),
            "probability": number(row, "probability"),
            "confidence": number(row, "confidence"),
        }
        for row in picks
    ]

    return {
        "updated": date.today().isoformat(),
        "week": week,
        "metrics": [
            {"label": "Market winner accuracy", "value": number(market, "accuracy"), "suffix": "%", "detail": "historical baseline"},
            {"label": "Walk-forward accuracy", "value": number(full_model, "accuracy"), "suffix": "%", "detail": "out-of-sample"},
            {"label": "Best confidence points", "value": number(best, "confidence_points"), "suffix": "%", "detail": best.get("strategy", "best strategy")},
        ],
        "strategies": strategies,
        "picks": rendered_picks,
        "method": [
            {"title": "Read the market", "text": "Convert moneylines into implied win probabilities and remove the bookmaker margin."},
            {"title": "Add team strength", "text": "Update ELO ratings chronologically so every prediction uses only information available at the time."},
            {"title": "Test forward", "text": "Train on past seasons and score the next one, repeating the process without leaking future results."},
            {"title": "Rank the card", "text": "Order predicted winners by confidence and assign each weekly weight exactly once."},
        ],
    }


def main() -> None:
    payload = json.dumps(build_dashboard(), indent=2)
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text(
        "// Generated by scripts/update_dashboard.py. Edit outputs/*.csv, not this file.\n"
        f"window.FOURTH_AND_DATA = {payload};\n",
        encoding="utf-8",
    )
    print(f"Updated {DESTINATION.relative_to(ROOT)}")


if __name__ == "__main__":
    main()

